config/routes.rb
PlanNto::Application.routes.draw do
 
namespace :admin do
  resources :payment_reports
  resources :users
  resources :click_reports
  resources :order_histories do
    collection do
      post "import"
    end
  end
  resources :advertisements do
    collection do
      get "change_ad_status"
      get "review"
      get "approved"
      get "denied"
    end
  end
  resources :buying_plans do
  collection do  
    get :search
    post :search
    get :proposal
    post :proposal_save
    get :proposal_list
   end
   member do
     get  :view_proposal
     get  :proposal_edit
   end
   end
  resources :feeds do
    member do
      get :add_vote
      get :approve
      get :reject
      post :content_action
    end
   end  
  resources :follows
  resources :source_categories, :only => [:index, :update]
 end
  match "sitemap.xml", :to => "sitemap#index", :defaults => {:format => :xml}
  get "home/index"
  resources :follows do
   collection do 
     get :user_follow
   end
  end   
  resources :error_messages

  match "/admin/impression_reports", :to => "admin/order_histories#index"
  match "/admin/orders", :to => "admin/order_histories#orders", :as => :admin_orders
  match "/admin/get_item_details", :to => "admin/order_histories#get_item_details"

  match "/admin/orders/edit/:id", :to => "admin/order_histories#edit", :as => :admin_order_edit
  match "/admin/orders/update", :to => "admin/order_histories#update", :as => :admin_order_update
  match "/admin/orders/delete", :to => "admin/order_histories#destroy", :as => :admin_order_destroy
  match "/admin/get_item_details", :to => "admin/order_histories#get_item_details"

  match "/terms_conditions" ,:to => "home#terms_conditions"
  match "/privacy_policy" ,:to => "home#privacy_policy"
  get "/contact_us" => "contact_us#new"
  match "/about_us",:to => "home#about_us"
  match "/opt_out",:to => "home#opt_out"
  match "/opt_out_submit",:to => "home#opt_out_submit"
  match "/targeting",:to => "home#targeting"
  match "/current_user_info",:to => "home#current_user_info"
  match "/external_page",:to => "products#external_page"
  match "/search_planto",:to => "products#search_items"
  
  match "/get_class_names",:to => "contents#get_class_names"
  match "/external_page",:to => "products#external_page"
  match "/where_to_buy_items",:to => "products#where_to_buy_items"
  match "/where_to_buy_items_vendor",:to => "products#where_to_buy_items_vendor"
  match "/widget_for_women",:to => "products#widget_for_women"
  match "/elec_widget_1",:to => "products#elec_widget_1"
  match "/price_vendor_details",:to => "products#price_vendor_details"
  match "/get_price_from_vendor",:to => "products#get_price_from_vendor"
  match "/price_text_vendor_details",:to => "products#price_text_vendor_details"
  match "/book_price_widget",:to => "products#book_price_widget"
  match "/sports_widget",:to => "products#sports_widget"
  match "/vendor_widget",:to => "products#vendor_widget"
  match "/product_offers",:to => "products#product_offers"
  match "/product_autocomplete",:to => "products#product_autocomplete"
  match "/get_item_for_widget",:to => "products#get_item_for_widget"
  match "/show_search_widget",:to => "products#show_search_widget"
  match "/get_item_item_advertisment",:to => "products#get_item_item_advertisment"
  
  match "/advertisement",:to => "products#advertisement"
  match "/get_class_names",:to => "contents#get_class_names"
  match "products/ratings",:to => "products#ratings"
  
  resources :contact_us
  resources :newuser_wizards do
  collection do
    get :product_select
    get :previous
  end
   member do
    get :product_delete
   end 
  end 
  
  match "/newuser_wizard", :to => "newuser_wizards#new"
  devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" ,:passwords => "users/passwords" } 
  resource :oauth,:controller=>"oauth" 

 match "oauth_callback" => "oauth#create"
 match "content_post" => "oauth#content_post"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  

  resources :history_details  
  resources :votes do
    collection do
      post "add_vote"
    end
  end
  match 'external_contents/:content_id' => 'external_contents#show', :as => 'external_content'
  
  match 'admin/search', :to => 'admin#index'
  match ':search_type/search' => 'search#index'
  resources :search do
    collection do
      get :autocomplete_items
      get :preference_items
      get :search_items
      get :autocomplete_source_items
      get :search_items_by_relavance
      get :search_items_by_relavance_housing
    end
  end
  match ':search_type/related-items/:car_id' => 'related_items#index'
  match 'groups/:id' => 'car_groups#show', :as => 'car_groups'
  match ':type/topics' => 'products#topics'
  match 'my_feeds'  => 'contents#my_feeds'

  
resources :field_values, :only => [:create]
resources :answer_contents  

resources :accounts do
    put :update
    member do
      put :change_password
      get :followers
      get :add_review
      get :add_information
      get :add_photo
    end
    collection do
      get :profile
     end 
  end
  match 'account_update', :to => "accounts#update", :as => "account_update"
  match 'personal_deals', :to => "preferences#personal_deals"
 
  resources :preferences do
    collection do
      get :give_advice
      get :owned_item
      get :considered_item_delete
      post :owned_description_save
      get :get_advice
      post :add_preference
      get :create_preference
      post :create_preference
      get  :deals_filter
      get :edit_preference
      post :save_advice
      get :update_preference
      get :plan_to_buy
      get :delete_buying_plan
      delete :delete_buying_plan
      get :update_question
      get :edit_user_question
      delete :delete_answer
      get :edit_answer
      post :update_answer
    end
    
  end
   match 'create_buying_plan' => 'preferences#new'
   match 'preferences/:search_type/:uuid' => 'preferences#show'
   match ':itemtype/guides/:guide_type' => 'contents#search_guide'
   match ':itemtype/:item_id/guides/:guide_type' => 'contents#search_guide'
   
  resources :cars do
        resources :reports
        resources :shares
  end
   

  resources :contents do
   resources :reports 
  collection do
    get :filter
    get :edit_guide_ajax
    post :update_guide
    get :feed
    get :feeds
    post :search_contents
    get :search_autocomplete_list
    get :search_related_contents
    get :quick_new
  end
  match "/contents/search" => 'contents#search'
 
  post :search
  resources :comments 
    collection do
      get :feed
    end
  end
resources :comments do
    resources :reports 
   end 
  resources :event_contents
  resources :plannto_contents
  resources :article_contents do
    put :download
    collection do
      post :download
      post :new_popup
      get :bmarklet
      put :download
    end
  end
  resources :mobiles do
        resources :shares
  end 
  resources :tablets do
        resources :shares
  end 
  resources :cameras do
        resources :shares
  end  
  resources :games do
        resources :shares
  end  
  resources :laptops do
        resources :shares
  end  
  resources :bikes do
        resources :shares
  end   
  resources :cycles do
        resources :shares
  end
  resources :lens do
    resources :shares
  end
  resources :televisions do
    resources :shares
  end
  resources :wearable_gadgets do
    resources :shares
  end
  resources :consoles do
    resources :shares
  end
  resources :beauties do
    resources :shares
  end
  resources :countries do
    resources :shares
  end
  resources :states do
    resources :shares
  end
  resources :cities do
    resources :shares
  end
  resources :places do
    resources :shares
  end
  resources :mobiles do 
    resources :reports
  end  
  resources :tablets do 
    resources :reports
   end 
  resources :vendors do 
    resources :reports
   end 
  resources :cameras do 
    resources :reports
  end  
  resources :bikes do
    resources :reports
  end  
  resources :cycles do
    resources :reports
  end
  resources :lens do
    resources :reports
  end
  resources :televisions do
    resources :reports
  end
  resources :wearable_gadgets do
    resources :reports
  end
  resources :consoles do
    resources :reports
  end
  resources :beauties do
    resources :reports
  end
  resources :countries do
    resources :reports
  end
  resources :states do
    resources :reports
  end
  resources :cities do
    resources :reports
  end
  resources :places do
    resources :reports
  end
  resources :bike_groups
  resources :manufacturers
  resources :car_groups  
  resources :attribute_tags
  resources :topics
  resource :facebook, :except => :create do
    get :callback, :to => :create
    get :friends
    get :wall_post
    get :show_friends
    post :wall_content
  end
  resources :products do
    collection do
      get 'related_items'
      get 'follow_buttons'
    end
    member do
      get 'related_products'
      get 'specification'
      get 'review_it'
      get 'add_item_info'
    end
  end
  resources :items do
       resources :reports    
    collection do
      get :compare
      get :update_page
      get :remove_duplicate_item
    end
    member do
      get 'follow_item_type'
      get 'plan_to_buy_item'
      get 'own_a_item'
      get 'follow_this_item'
    end
  end
  resources :reviews
  resources :review_contents
  resources :question_contents
  resources :pros
  resources :questions
  resources :answers
  resources :tips
  resources :invitations
  resources :processes, :only => [:index] do
    collection do
      get "item_update"
    end
  end

  match 'invitation/accept/:token' => "invitations#accept", :as => :accept_invitation
    
  resources :imageuploads, :only => [:show] 
  match "/imageuploads_tag" => 'imageuploads#tag' 

app/models/content_action.rb
class ContentAction < ActiveRecord::Base
end

app/views/contents/_activity.html.erb
<%if content.is_a?(UserActivity) %>
  <div id="activity_<%= page %><%= content.related_activity_type != 'User' ? content.related_id
: '' %>">
   <%if content.related_activity =="followed" &&  content.related_activity_type == "User"%>
       <a class="txt_brown_bold" href="<%= content.user.get_url()%>"><%= content.user.name %></a>
	     <a class="txt_brown_bold"> <%= content.related_activity + " " %> </a>
      <% u = User.find(content.related_id) %>
      <a class="txt_brown_bold" href="<%= u.get_url()%>">
      <%= u.name %> </a> <a class="txt_brown_bold"> - <%= time_ago_format(content)%> ago.</a>
   <div class="mainContentDiv">
    <div style="width:100px;height:120px;">
     <%= image_tag(u.get_photo(:medium)) %></div> <br /> </div>
  <%elsif !content_ids.include?(content.related_id)%>

     <% unless  content.related_activity == "created" || content.related_activity == "answered" %>

 <span id="username_<%= page %><%= content.related_id%>"> <a class="txt_brown_bold" href="<%= content.user.get_url()%>"> <%= content.user.name %></a> </span>
	<span id="related_activity_<%= page %><%= content.related_id%>"> <a class="txt_brown_bold">  <%= content.related_activity + " " %> </a> </span>
<a class="txt_brown_bold"><%= indefinite_articlerize(content.related_activity_type.singularize) %></a> <a class="txt_brown_bold"> - <%= time_ago_format(content)%> ago.</a>
  <%end%>
<%elsif  content_ids.include?(content.related_id) %>
  <% unless  content.related_activity == "created" || content.related_activity == "answered"  %>
    <script>
       if ($("#activity_<%= page %><%= content.related_activity_type != 'User' ? content.related_id :  ''%>").val().to_string == "")
      {
        $("#activity_<%= page %><%= content.related_activity_type != 'User' ? content.related_id :  ''%>").html('<span id="username_<%= page %><%= content.related_id%>"> <a class="txt_brown_bold" href="<%= content.user.get_url()%>">  <%= content.user.name %></a></span> <span id="related_activity_<%= page %><%= content.related_id%>"> <a class="txt_brown_bold"><%= content.related_activity + " " %> </a></span><a class="txt_brown_bold"><%= indefinite_articlerize(content.related_activity_type.singularize) %></a> <a class="txt_brown_bold"> - <%= time_ago_format(content)%> ago.</a>')
      }
      else
      {
       if ($("#username_<%= page %><%= content.related_id%>").text().indexOf('<%= escape_javascript(content.user.name) %>') == -1 )
       {
      $("#username_<%= page %><%= content.related_id%>").append("<a class='txt_brown_bold' href='<%= escape_javascript(content.user.get_url()) %>'>, <%= escape_javascript(content.user.name) %></a>");
      }
       if ($("#related_activity_<%= page %><%= content.related_id%>").text().indexOf('<%= content.related_activity%> ') == -1)
       {
      $("#related_activity_<%= page %><%= content.related_id%>").append("<a class='txt_brown_bold'>/<%= escape_javascript(content.related_activity + " ") %></a>");
   }
      }

    </script>
 <%end%>
<%end%>
</div>
<%else %>

<div id="activity_<%= page %><%= content.id %>"> </div>

<%end%>

app/views/contents/_article.html.erb
<% cache ['part-1', content] do %>
<div class="mainContentDiv" id="mainContentDiv<%=content.id%>">
  <%=render :partial => "votes/voting_detail", :locals => {:item => content, :user => user_signed_in? ? current_user : nil}%>
  <div class="float_rgt">
   <a href="<%= content.user.get_url() rescue ''%>">  <img src="<%=content.user.get_photo rescue ''%>" class="userImageSmall"/>   </a>
  </div>
  <div id="content_<%= content.id  %>" class="subContentDiv">


    <div>
      <%= link_to content.title, content_path(content.id), :class => "title txt_onhover" %><%if content.sent_approval? %> <font color="black" style="font-style:italic">[Under Review] </font> <%end%>
        <%if content.sub_type == "Deals"  %>
           <%if content.deal_expired? %>
             <font color="black" style="font-style:italic">[This Deal is Expired.] </font>
           <%end%>
        <%end%>     
          
       <% if content.url?  %>
        - (<a class="txt_black_description txt_onhover" style="cursor: pointer; cursor: hand;" href="/external_contents/<%= content.id %>"><%=  URI.parse(URI.encode(URI.decode(content.url))).host.gsub("www.","") rescue ''%> </a>)
       <%end%>
    </div>
    <div><a class="txt_brown_bold" href="<%= content.user.get_url() rescue ''%>"><%= content.user.name rescue '' %></a><a class="txt_brown"> shared a <%= content.sub_type.singularize %> on </a><a class="txt_brown"><%=get_anchor_name_link(content)%></a> <a class="txt_brown">- <%end%><%= time_ago_format(content)%><% cache ['part-2', content] do %> ago </a></div>
    <div class="contentsubsection">
      
      <%if content.thumbnail?%>
      <div style="float:left;width:80px;padding-right:10px;"><div><img src="<%= content.thumbnail %>" class="uploadedarticleContentdisplay float_lft"/></div></div>
        <div style="float:left;width:490px;">
    
      <%end%>
    
          <div class="subContentGap">
            <%= raw get_rating_or_category_contents(content,page)%>
       
                <% if content.sub_type == "#{ArticleCategory::REVIEWS}" %>
                <% rating =  (content.is_a?ArticleContent) ? content.field1 : content.rating %>
               <script type="text/javascript">
                  $('div#content_show_<%= content.id%><%= page%>').raty({
                  starOff:  'assets/star-off.png',
                  starHalf   : 'assets/star-half.png',
                  half       : true,
                  readOnly   : true,
                  starOn: 'assets/star-on.png',
                  start: <%= "#{rating.to_f.round(1)}"%>
                      });
                </script>
                <%end%>
            <%= raw get_content_description(content)%>
        </div>
       <%if content.thumbnail?%> 
        </div>
        <%end%>
      <div class="subContentGap"></div>      
      <%= raw get_pro_con_verdict(content)%>     
    </div>

    <ul class="divCommentsConent dontfloat">
      <li class="subContentGap float_lft"><a class="txt_blue " style="float:left;"><img src="/images/comment.jpg"/><%= render_comments_anchor(content).html_safe %></a></li>
      <li class="subContentGap float_lft"><a class="txt_gray ">|</a></li>
      <li class="subContentGap float_lft"><a class="txt_blue " style="float:left;"><img src="/images/report.jpg"/><%= link_to "Report",new_content_report_path(content,:type => "content"),:remote => true,:class => "txt_blue" ,:id => "report_link_#{content.id}",:style=>"float:left;padding-left:5px;"%></a></li>
    		 
        <div id="edit_actions_<%= content.id %>"> </div>
    </ul>
  </div>
    <%@fromcontent = "true"%>
  <%=render :partial => "comments/new", :locals => { :content => content, :fromcontent => @fromcontent}  %>
</div>
<%end%>

app/views/contents/_plan_to_buy_items.html.erb
<table width="251" height="38" border="0" cellspacing="0" cellpadding="0" style="border:solid 1px #cdd3d7;">
    <tr>
      <td class="bg_widgethdr txt_white">Plan To Buy Products</td>
    </tr>
    <tr>
      <td valign="top">
       <table width="226" border="0" cellspacing="0" cellpadding="0" align="center">
          <% @buyer_items.each do |item|%>
           <tr>
            <td width="113" height="85"><a href="<%=(item.get_url()) rescue ''%>"><img src="<%= item.image_url rescue ''%>" width="92" height="69"/></td>
            <td width="113">
            <div>
            <a href="<%=item.get_url() rescue ''%>" class="txt_black txt_onhover"><%= item.name rescue ''%></a>
             
           </div>
           <a class="txt_price"><%= item.get_price_info('Price',false) %></a><br />
            <%if item.rated_users_count > 0 %>
           <div>
           <div style="float:left;">
           <a class="txt_normal" href="<%= item.get_url + '?fl=Reviews'%>">
            <%= render :partial => 'shared/rating',:locals => {:item => item, :rating_id => "related_item_id#{item.id}"} %> 
           </a></div>        

           <div class="txt_blue" style="float:right;" >
           <a class="txt_blue" href="<%= item.get_url + '?fl=Reviews'%>"> <%= "(" + item.rated_users_count.to_s + ")" %></a></div>
           
         </div>
           <br />
          <%end%>
            </td>
          </tr>
         <%end%>
           <tr >
            <td height="33" class="" colspan="2" style="border-top:solid 1px #cdd3d7;width:100%;"><a href="<%= "/" + "#{current_user.username}"%>" class="txt_blue">View All</a></td>
          </tr>
        </table>
        </td>
    </tr>
   
  </table>
  <br/>
<br />

app/views/contents/_review.html.erb
<% cache ['part-1', content] do %>
<div class="mainContentDiv" id="mainContentDiv<%=content.id%>">
  <%=render :partial => "votes/voting_detail", :locals => {:item => content, :user => user_signed_in? ? current_user : nil}%>
  
  <div class="float_rgt">
    <a href="<%= content.user.get_url()%>">  <img src="<%=content.user.get_photo%>" class="userImageSmall"/>   </a>
    </div>
  <div id="content_<%= content.id  %>" class="subContentDiv">
    <div><%= link_to content.title, content_path(content.id), :class => "title txt_onhover" %><%if content.sent_approval? %> <font color="black" style="font-style:italic">[Under Review] </font> <%end%></div>
 
   <div><a class="txt_brown_bold" href="<%= content.user.get_url()%>"><%= content.user.name %></a><a class="txt_brown"> reviewed </a><%=get_anchor_name_link(content)%> <a class="txt_brown">- <%end%><%= time_ago_format(content)%><% cache ['part-2', content] do %> ago </a></div>
    <div class="contentsubsection">
        <%if content.thumbnail?%>
				  <div><img src="<%= content.thumbnail %>" class="uploadedarticleContentdisplay float_lft"/>
				  </div>
				<%end%>
				<div class="subContentGap">
    	<%= raw get_rating_or_category_contents(content,page)%>
						<% if content.sub_type == "#{ArticleCategory::REVIEWS}" %>
						<% rating =  (content.is_a?(ArticleContent)) ? content.field1 : content.rating %>
						<script type="text/javascript">
							$('div#content_show_<%= content.id%><%= page %>').raty({
							starOff:  'assets/star-off.png',
							starHalf   : 'assets/star-half.png',
							half       : true,
							starOn: 'assets/star-on.png',
							start: <%= "#{rating.to_f.round(1)}"%>
									});
						</script>
						<%end%>
    </div>
   <!-- <div class="subContentGap">	<a class="titlePro">Pro:</a><a class="txt_black_description"><%#= content.pros %></a></div>
    <div class="subContentGap"><a class="titleCon">Con:</a><a class="txt_black_description"><%#= content.cons %></a></div>-
  -->
    <div class="subContentGap"><%= raw get_content_description(content)%></div>
    </div>
    <ul class="divCommentsConent">
      <li class="subContentGap float_lft"><a class="txt_blue" style="float:left;"><img src="/images/comment.jpg"/><%= render_comments_anchor(content).html_safe  %></a></li>
      <li class="subContentGap float_lft"><a class="txt_gray">|</a></li>
      <li class="subContentGap float_lft"><a class="txt_blue" style="float:left;"><div id="report_link_<%= content.id %>"> <img src="/images/report.jpg"/><%= link_to "Report",new_content_report_path(content,:type => "content"),:remote => true,:class => "txt_blue" ,:style=>"float:left;padding-left:5px;"%></div></a></li>
      
     
       <div id="edit_actions_<%= content.id %>"> </div>
    </ul>
  </div>
  <%@fromcontent = "true"%>
  <%=render :partial => "comments/new", :locals => { :content => content, :fromcontent => @fromcontent}  %>
</div>
<%end%>

app/views/contents/_show_question_details.erb
<%= render 'shared/product_button_javascript', :button_class => '', :item => content, :related_follower => user_follow_type(content, current_user) , :related_items => false %>
<%= render 'shared/show_hide_login_form', :item => content %>
<div style="padding-left:60px;width:600px;">
 <ul id="productList" class="tagging">
		<%  Item.where("id in (#{content.related_items.collect(&:item_id).join(',')})").each do |item|%>
		<%= display_product_tag(item, false).html_safe%>
		<% end%>
	</ul>
</div>

     
<div class="float_rgt" >
   <%= render 'shared/follow_buttons',:follow_type => content.content_type, :follow_html => '', :button_class => '', :item => content, :related_items => false %>
</div>
<script>
 $(".plan_to_follow_icon").click(function(e){
  <%if !current_user %>
   $("#login #click_message").show();
         $("#login #click_message").html("<%= escape_javascript(render  '/shared/login_popup_message',:type => 'content-follow')%>");
         <%end%>

      });
 </script>
<div class="leftcolumnbig" style="clear:both;">
<!-- Product Details - Start -->
<div class="contentDetailsMainDiv">
      
        <!-- Question - Start -->
        <div  class="mainContentDiv">   
                   
      <%=render :partial => "votes/voting_detail", :locals => {:item => content, :user => user_signed_in? ? current_user : nil}%>
      
      <div  class="float_rgt">
        <img src="<%=content.user.get_photo%>" class="userImageSmall"/>
      </div>

      <div  class="subContentDiv">
                <div><a class="title"><%= content.title %></a><%if content.sent_approval? %> <font color="black" style="font-style:italic">[Under Review] </font> <%end%></div>
                <div><a class="txt_brown">Asked by <%= content.user.name %> - <%= time_ago_in_words(content.created_at) %> ago</a></div>
                <div class="subContentGap">
                <%if content.thumbnail?%>
						 	     <div><img src="<%= content.thumbnail %>" class="uploadedarticleContentdisplay float_lft"/></div>
						 	<%end%>
                <%= raw get_content_description(content, true)%></div>
                <ul class="divCommentsConent">
                    <li class="subContentGap float_lft" ><a class="txt_blue "><%= render_comments_anchor(content).html_safe  %></a></li>
                    <li class="subContentGap float_lft"><a class="txt_gray ">|</a></li>
                    <li class="subContentGap float_lft"><a class="txt_blue "><%= link_to "Report",new_content_report_path(content,:type => "content"),:remote => true,:class => "txt_blue",:id => "report_link_#{content.id}" %></a>
						</li>
					<script>
        $("#report_link_<%= content.id %>").click(function(e){
          <%if !current_user %>
         $("#login-1 #click_message").html("<%= escape_javascript(render  '/shared/login_popup_message',:type => 'report')%>");
            openLoginPopup("#" + $(this).attr('id'), "click");
            return false
          <%end%>
        })
        </script>
                    <%if content.can_update_content?(current_user)%>
                    <!--<li class="subContentGap float_lft"><a class="txt_gray ">|</a></li>
                    <li class="subContentGap float_lft"><%=link_to "Delete This", content_path(content), :method => "delete", :remote => true,:confirm => "Are you sure you want to delete #{content.title}?", :class => "txt_blue"%></li>
                    
                    <li class="subContentGap float_lft"><a class="txt_gray ">|</a></li>
                    <li class="subContentGap float_lft"><%=link_to "Update This", edit_content_path(content, :detail => true), :remote => true, :class => "txt_blue"%></li> -->
                      <%= render :partial  => 'contents/guide', :locals => {:content =>  content} %>
                    <%end%>
                    <%@detail = "true" %>
                    <%= render :partial  => 'contents/others_action', :locals => {:content => content,:detail => @detail} %>
                </ul>
      </div>
      <%=render :partial => "comments/new", :locals => { :content => content}  %>
    </div>
    <!-- Question - End -->
    
    <!-- Answer this question - Start -->
      <div  style="border-bottom:solid 1px #ccd4d8;">
        <div class="hdr_Category float_lft margin_lft10"><%= pluralize(content.answer_contents.where("status!=?", Content::DELETE_STATUS).count,'Answers') %> </div>
        <div class="float_rgt" style="margin-top:8px;">
               <!-- <a style="" class="btn_submitanswer answer_button" id="answer_this_question" >Answer this Question</a> --> 
            
                </div>
                
      </div>
      <div  style="border-top:solid 1px #ccd4d8;clear:both;"></div>
    <!-- Answer this question - End -->
   
  <div id="answer_content_div">      
  <%= render :partial => 'answer_contents/answer_content',:collection => content.answer_contents.where("status!=?", Content::DELETE_STATUS) %>
  </div>
     <%= render :partial => 'answer_contents/new_answer_content', :locals => {:question_content => content, :item => @item ,:content => AnswerContent.new}%>
        <script>
          $("#publishanswer").click(function(e){
            <% if !current_user %>
             $("#login #click_message").show();
               $("#login #click_message").html("<%= escape_javascript(render  '/shared/login_popup_message',:type => 'answer')%>");
           <%end%>
        });
           </script>
    
</div>


<!-- Product Details - End -->


</div>

<div class="rightcolumnsmall">
  <br/>
  <div style="border-top:solid 1px #cdd3d7;padding:10px 0px 10px 0px;">
   <%= render  "shared/share_buttons",:caption_text => content.title +  ' -PlannTo.com' %>
  </div>

  <%= render "contents/related_contents"%>
  <%= render "contents/popular_items"%>

<!-- Related Cars -- End -->
</div>

<!-- This will go into main layout -->
</div>

app/views/contents/destroy.js.erb
$("#mainContentDiv<%=@item.id%>").remove();

app/views/contents/edit_guide_ajax.js.erb
<%@contents.each do |content| %>
   $("#edit_actions_<%= content.id %>").html('<%= escape_javascript(render 'contents/edit_guide_actions', :content => content) %>');
<%end%>   

app/views/contents/feed.html.erb
<span class="sortby">
   <span><b>Sort by:</b></span>
     <a class="txt_blue" id="link_active"  href="#">Relevance</a> <span style="padding:0px 5px;">|</span>
     <a class="txt_blue" href="#">Newest</a> <span style="padding:0px 5px;">|</span>
     <a class="txt_blue" href="#">Most Answers</a>
 </span>
<%= render :partial => 'contents', :locals => {:params => params} %>

app/views/contents/my_feeds.js.erb
element= jQuery('#content_next')
//element.before('<%#=escape_javascript(contents_string.html_safe) %>');
running=false;
$("#filter_page_no").val("2");
$("#items").val("<%= @items%>");
$("#item_types").val("<%= @item_types %>");
$("#content_search_item_ids").val("<%= @items%>");
$("#content_search_itemtype_ids").val("<%= @items%>");
$("#contentsList").html('<%= escape_javascript(render :partial => 'contents/contents') %>');
element.remove();
//$("#filter_page_no").val("<%#=@contents.current_page+ 1%>");