config/routes.rb
PlanNto::Application.routes.draw do
 
namespace :admin do
  resources :payment_reports
  resources :users
  resources :click_reports
  resources :order_histories do
    collection do
      post "import"
    end
  end
  resources :advertisements do
    collection do
      get "change_ad_status"
      get "review"
      get "approved"
      get "denied"
    end
  end
  resources :buying_plans do
  collection do  
    get :search
    post :search
    get :proposal
    post :proposal_save
    get :proposal_list
   end
   member do
     get  :view_proposal
     get  :proposal_edit
   end
   end
  resources :feeds do
    member do
      get :add_vote
      get :approve
      get :reject
      post :content_action
    end
   end  
  resources :follows
  resources :source_categories, :only => [:index, :update]
 end
  match "sitemap.xml", :to => "sitemap#index", :defaults => {:format => :xml}
  get "home/index"
  resources :follows do
   collection do 
     get :user_follow
   end
  end   
  resources :error_messages

  match "/admin/impression_reports", :to => "admin/order_histories#index"
  match "/admin/orders", :to => "admin/order_histories#orders", :as => :admin_orders
  match "/admin/get_item_details", :to => "admin/order_histories#get_item_details"

  match "/admin/orders/edit/:id", :to => "admin/order_histories#edit", :as => :admin_order_edit
  match "/admin/orders/update", :to => "admin/order_histories#update", :as => :admin_order_update
  match "/admin/orders/delete", :to => "admin/order_histories#destroy", :as => :admin_order_destroy
  match "/admin/get_item_details", :to => "admin/order_histories#get_item_details"

  match "/terms_conditions" ,:to => "home#terms_conditions"
  match "/privacy_policy" ,:to => "home#privacy_policy"
  get "/contact_us" => "contact_us#new"
  match "/about_us",:to => "home#about_us"
  match "/opt_out",:to => "home#opt_out"
  match "/opt_out_submit",:to => "home#opt_out_submit"
  match "/targeting",:to => "home#targeting"
  match "/current_user_info",:to => "home#current_user_info"
  match "/external_page",:to => "products#external_page"
  match "/search_planto",:to => "products#search_items"
  
  match "/get_class_names",:to => "contents#get_class_names"
  match "/external_page",:to => "products#external_page"
  match "/where_to_buy_items",:to => "products#where_to_buy_items"
  match "/where_to_buy_items_vendor",:to => "products#where_to_buy_items_vendor"
  match "/widget_for_women",:to => "products#widget_for_women"
  match "/elec_widget_1",:to => "products#elec_widget_1"
  match "/price_vendor_details",:to => "products#price_vendor_details"
  match "/get_price_from_vendor",:to => "products#get_price_from_vendor"
  match "/price_text_vendor_details",:to => "products#price_text_vendor_details"
  match "/book_price_widget",:to => "products#book_price_widget"
  match "/sports_widget",:to => "products#sports_widget"
  match "/vendor_widget",:to => "products#vendor_widget"
  match "/product_offers",:to => "products#product_offers"
  match "/product_autocomplete",:to => "products#product_autocomplete"
  match "/get_item_for_widget",:to => "products#get_item_for_widget"
  match "/show_search_widget",:to => "products#show_search_widget"
  match "/get_item_item_advertisment",:to => "products#get_item_item_advertisment"
  
  match "/advertisement",:to => "products#advertisement"
  match "/get_class_names",:to => "contents#get_class_names"
  match "products/ratings",:to => "products#ratings"
  
  resources :contact_us
  resources :newuser_wizards do
  collection do
    get :product_select
    get :previous
  end
   member do
    get :product_delete
   end 
  end 
  
  match "/newuser_wizard", :to => "newuser_wizards#new"
  devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" ,:passwords => "users/passwords" } 
  resource :oauth,:controller=>"oauth" 

 match "oauth_callback" => "oauth#create"
 match "content_post" => "oauth#content_post"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  

  resources :history_details  
  resources :votes do
    collection do
      post "add_vote"
    end
  end
  match 'external_contents/:content_id' => 'external_contents#show', :as => 'external_content'
  
  match 'admin/search', :to => 'admin#index'
  match ':search_type/search' => 'search#index'
  resources :search do
    collection do
      get :autocomplete_items
      get :preference_items
      get :search_items
      get :autocomplete_source_items
      get :search_items_by_relavance
      get :search_items_by_relavance_housing
    end
  end
  match ':search_type/related-items/:car_id' => 'related_items#index'
  match 'groups/:id' => 'car_groups#show', :as => 'car_groups'
  match ':type/topics' => 'products#topics'
  match 'my_feeds'  => 'contents#my_feeds'

  
resources :field_values, :only => [:create]
resources :answer_contents  

resources :accounts do
    put :update
    member do
      put :change_password
      get :followers
      get :add_review
      get :add_information
      get :add_photo
    end
    collection do
      get :profile
     end 
  end
  match 'account_update', :to => "accounts#update", :as => "account_update"
  match 'personal_deals', :to => "preferences#personal_deals"
 
  resources :preferences do
    collection do
      get :give_advice
      get :owned_item
      get :considered_item_delete
      post :owned_description_save
      get :get_advice
      post :add_preference
      get :create_preference
      post :create_preference
      get  :deals_filter
      get :edit_preference
      post :save_advice
      get :update_preference
      get :plan_to_buy
      get :delete_buying_plan
      delete :delete_buying_plan
      get :update_question
      get :edit_user_question
      delete :delete_answer
      get :edit_answer
      post :update_answer
    end
    
  end
   match 'create_buying_plan' => 'preferences#new'
   match 'preferences/:search_type/:uuid' => 'preferences#show'
   match ':itemtype/guides/:guide_type' => 'contents#search_guide'
   match ':itemtype/:item_id/guides/:guide_type' => 'contents#search_guide'
   
  resources :cars do
        resources :reports
        resources :shares
  end
   

  resources :contents do
   resources :reports 
  collection do
    get :filter
    get :edit_guide_ajax
    post :update_guide
    get :feed
    get :feeds
    post :search_contents
    get :search_autocomplete_list
    get :search_related_contents
    get :quick_new
  end
  match "/contents/search" => 'contents#search'
 
  post :search
  resources :comments 
    collection do
      get :feed
    end
  end
resources :comments do
    resources :reports 
   end 
  resources :event_contents
  resources :plannto_contents
  resources :article_contents do
    put :download
    collection do
      post :download
      post :new_popup
      get :bmarklet
      put :download
    end
  end
  resources :mobiles do
        resources :shares
  end 
  resources :tablets do
        resources :shares
  end 
  resources :cameras do
        resources :shares
  end  
  resources :games do
        resources :shares
  end  
  resources :laptops do
        resources :shares
  end  
  resources :bikes do
        resources :shares
  end   
  resources :cycles do
        resources :shares
  end
  resources :lens do
    resources :shares
  end
  resources :televisions do
    resources :shares
  end
  resources :wearable_gadgets do
    resources :shares
  end
  resources :consoles do
    resources :shares
  end
  resources :beauties do
    resources :shares
  end
  resources :countries do
    resources :shares
  end
  resources :states do
    resources :shares
  end
  resources :cities do
    resources :shares
  end
  resources :places do
    resources :shares
  end
  resources :mobiles do 
    resources :reports
  end  
  resources :tablets do 
    resources :reports
   end 
  resources :vendors do 
    resources :reports
   end 
  resources :cameras do 
    resources :reports
  end  
  resources :bikes do
    resources :reports
  end  
  resources :cycles do
    resources :reports
  end
  resources :lens do
    resources :reports
  end
  resources :televisions do
    resources :reports
  end
  resources :wearable_gadgets do
    resources :reports
  end
  resources :consoles do
    resources :reports
  end
  resources :beauties do
    resources :reports
  end
  resources :countries do
    resources :reports
  end
  resources :states do
    resources :reports
  end
  resources :cities do
    resources :reports
  end
  resources :places do
    resources :reports
  end
  resources :bike_groups
  resources :manufacturers
  resources :car_groups  
  resources :attribute_tags
  resources :topics
  resource :facebook, :except => :create do
    get :callback, :to => :create
    get :friends
    get :wall_post
    get :show_friends
    post :wall_content
  end
  resources :products do
    collection do
      get 'related_items'
      get 'follow_buttons'
    end
    member do
      get 'related_products'
      get 'specification'
      get 'review_it'
      get 'add_item_info'
    end
  end
  resources :items do
       resources :reports    
    collection do
      get :compare
      get :update_page
      get :remove_duplicate_item
    end
    member do
      get 'follow_item_type'
      get 'plan_to_buy_item'
      get 'own_a_item'
      get 'follow_this_item'
    end
  end
  resources :reviews
  resources :review_contents
  resources :question_contents
  resources :pros
  resources :questions
  resources :answers
  resources :tips
  resources :invitations
  resources :processes, :only => [:index] do
    collection do
      get "item_update"
    end
  end

  match 'invitation/accept/:token' => "invitations#accept", :as => :accept_invitation
    
  resources :imageuploads, :only => [:show] 
  match "/imageuploads_tag" => 'imageuploads#tag' 

app/controllers/home_controller.rb
class HomeController < ApplicationController
caches_action :index, :unless => :current_user, :cache_path => Proc.new { |c| c.params }
caches_action :terms_conditions,  :cache_path => Proc.new { |c| c.params }
caches_action :privacy_policy,  :cache_path => Proc.new { |c| c.params }
caches_action :about_us,  :cache_path => Proc.new { |c| c.params }
caches_action :targeting, :unless => :current_user,  :cache_path => Proc.new { |c| c.params }
layout false, only: [:targeting]
  layout "product"
   def index
     @itemtypes_list =  Itemtype.where("itemtype in (?)", Item::ITEMTYPES-["Manufacturer","Car Group","Topic"])      
    # if current_user
    #   get_objects_for_my_feeds
    #   render "contents/my_feeds"
    # else
      @homepage = "true"
      @static_page = "true"
      @static_page1 = "true"
      render :index
    # end
      
   end

  def terms_conditions
    @static_page ="true"
  end
  
  def privacy_policy
   @static_page ="true"
   @homepage = "false"
  end
  
  def about_us
    @static_page ="true"
  end
  
  def opt_out
    @static_page ="true"
    @homepage = "false"
  end
  
  def opt_out_submit
    unless cookies[:plan_to_temp_user_id].blank?
      user_id = cookies[:plan_to_temp_user_id]

      #delete form buyinglist plannto
      u_key = "u:ac:plannto:#{user_id}"
      del_key = "users:buyinglist:plannto:#{user_id}"
      $redis.del(u_key)
      $redis_rtb.del(del_key)

      #delete from buyinglist
      u_key = "u:ac:#{user_id}"
      del_key = "users:buyinglist:#{user_id}"
      $redis.del(u_key)
      $redis_rtb.del(del_key)

      cookies.delete :plan_to_temp_user_id
    end
    cookies[:plannto_optout] = { value: "true", expires: 1.year.from_now } if cookies[:plannto_optout].blank?
    @static_page ="true"
  end

   def targeting
    render :layout => false
  end
 def dialog_test
 
 end

 def current_user_info
  render partial: "shared/header_right_part"

 end
 private
 
 def get_objects_for_my_feeds
     @buying_plan = params[:buying_plan]
     @buying_plans = BuyingPlan.where("user_id = ? and (deleted  IS NULL or deleted = 0)",   current_user.id)
   @items,@item_types,@article_categories,@root_items = Content.follow_items_contents(current_user,params[:item_types],params[:type])
      filter_params = {"sub_type" => @article_categories}
      filter_params["itemtype_id"] = @item_types 
      @follows,@followers = Follow.get_followers_following(current_user,"Followers",1,24)
      @follows,@following = Follow.get_followers_following(current_user,"Following",1,24)
      @follow_items = Item.get_follows_items_for_user(current_user)
      @owned_items = Item.get_owned_items_for_user(current_user)
      @buyer_items = Item.get_buyer_items_for_user(current_user)
      if @items.size > 0 and !@item_types.blank?
        if @items.is_a? Array
            items = @items
        else
          items = @items.split(",")
        end
       filter_params["items_id"] = items
       filter_params["content_ids"] = Content.follow_content_ids(current_user,@article_categories)
       filter_params["status"] = 1
       filter_params["created_by"] = User.get_follow_users_id(current_user)
       filter_params["page"] = 1
       filter_params["root_items"] = @root_items
       filter_params["guide"] = params[:guide] if params[:guide].present?
       filter_params["order"] = "created_at desc"
       @contents = Content.my_feeds_filter(filter_params,current_user)
    end
 end   
 end
 

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/dialog_test.html.erb
<html>
<head>
<title>test</title>

<script type="text/javascript">

    $(function() {

        $('#modal').click(function() {
            $('#datamodal').dialog({modal: true,height: 480,width: 275});
        });

    });

</script>

</head>
<body>
    <input id="modal" type="button" value="show modal" />
    <div id="datamodal" style="border:10px solid #999;backgroundColor:#FFFFFF;color:#111111;display:none;padding:10px;">
        Test this out..
        <input type="text"></input>
    </div>
</body>
</html>

app/views/home/opt_out.erb
<div  style="line-height:16px;">
<h3> Opt Out </h3>
<br/>

The persistent cookie that we use for advertising is created to track what are the product advertisements served to you so that we can avoid showing the same advertisement multiple times to you or serve the advertisement that is interesting to you. We also use this information for reporting and analysing the data. This cookie doesn’t contain any of your personal information. You can opt out of this cookie tracking by clicking the button shown below.

<br/>
<br/>

<%= button_to "Opt Out", {action: "opt_out_submit"} %>

<br/>

Note - If you choose to opt out, we create a additional opt-out cookie when you click on this button.  We rely on this cookie to identify you as an opted-out user. We will not track your anonymous user behaviour data or show customised advertisements if you have opted-out. However, you might be shown ads that are not customised based on your interests and preferences but based on the content/context of the web page.

<br/>
</div>

app/views/home/opt_out_submit.erb
You have been opted out of cookie tracking successfully.

app/views/home/targeting.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />

	<title>PlannTo Targeting - Right Advertisements at Right Place</title>
	<meta name="description" content="">
	<meta name="author" content="">
	<meta name="HandheldFriendly" content="true">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!-- Import CSS -->
	<link rel="stylesheet" href="/stylesheets/targeting/main.css">
	<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
	<script src="/javascripts/targeting/jquery.min.js"></script>
	<script src="/javascripts/targeting/jquery.easing.min.js"></script>
	<script src="/javascripts/targeting/jquery.scrollto.min.js"></script>
	<script src="/javascripts/targeting/slabtext.min.js"></script>
	<script src="/javascripts/targeting/jquery.nav.js"></script>
	<script src="/javascripts/targeting/main.js"></script>
	<link href='<%= configatron.root_image_path %>static/images/logosc.png' rel='shortcut icon' type='image/x-icon'>
</head>
<!-- To change color change the class "color-1" to "color-2, color-3 ... color-6" -->
<body class="home color-2">
	<div id="header">
		<div class="container">

			<div class="row">

					<i id="nav-button" class="icon-circle-arrow-down"></i>
					<h2 id="logo"><a href=""> <span class="highlight" style="text-transform: none;font-weight: 600;letter-spacing: 1px;">PlannTo</span></a></h2>
				

				<div id="top-nav" class="">
					<ul id="fixed-nav">
						<li class="current"><a href="#home">Home</a></li>
							<li><a href="#advertisement">Advertisements</a></li>
						<li><a href="#services">Services</a></li>
						<li><a href="#aboutus">About Us</a></li>
						<li><a href="#contact">Contact Us</a></li>
                        <li><%= link_to "Products", home_products_path, :class => "external" %></li>
                          <% if current_user %>
                              <li><%= link_to "Logout", destroy_user_session_path, :class => "external" %></li>
                          <% else %>
                              <li><%= link_to "Sign In", new_user_session_path, :class => "external" %></li>
                          <% end %>
                        </li>
					</ul>
				</div>

			</div>
		</div>
	</div><!-- End Header -->
	<!-- Big Full screen Banner -->
	<div class="hero bg-fixed bg-color" id="home">

		<div class="slogan">
			<div  class="vcenter container">

				<div class="row">

					<div class="span12">
						<h1>We Deliver Right Advertisements at Right Place.</h1>
					</div>
				</div>
			</div>
		</div>


	</div>
	<!-- End Full screen banner  -->
	<!-- Services Section -->
	<!-- class section-alt is to give a different color please edit css/style.css to change the color -->
	<div class="section section-alt" id="services">
		<div class="container">
			<div class="content">
				<div class="row" >
					<div class="title">
						<h2>Our Services</h2>
						<div class="hr hr-small hr-center"><span class="hr-inner"></span></div>
						<p>We provide solutions for delivering the right advertisements at the right place using our contextual advertisement platform.</p>
					</div>
				</div>
				<div class="row">
					<div class="span4 i-block">
						<h3>Product Based Contextual Targeting</h3>
						<p>Advertisers -  PlannTo supports contextual targeting at an individual product level and it helps advertisers to connect with prospective buyer of their product using its advanced contextual intelligence and semantic tagging platform. <a href="#advertisement" style="color: gray;font-style: italic;font-size: 12px;">More Details</a></p>
					</div>
					<div class="span4 i-block">
						<h3>Dynamic Display/Video Advertisements</h3>
						<p>Advertisers - PlannTo complements the product level targeting with its dynamic display/video advertising solutions. With the real time targeted dynamic display and video advertisements, advertisers can deliver customised, precisely targeted & personalised advertisement with right content at right moment at right place every time. <a href="#advertisement" style="color: gray;font-style: italic;font-size: 12px;">More Details</a></p>
					</div>
					<div class="span4 i-block">
						<h3>Intent Based Audience Targeting</h3>
						<p>Advertisers - Target a user based on their intent. For example, advertiser can show an advertisement to an user if he is intent to buy a mobile within certain price range. Intent of the user is captured from the content user is reading. <a href="#advertisement" style="color: gray;font-style: italic;font-size: 12px;">More Details</a></p>
					</div>
				</div>
				<div class="hr hr-invisible"></div>
				<div class="row">
					<div class="span4 i-block">
						<h3>Best Prices Widget </h3>
						<p>For Publishers - Show the best prices of the product discussed in that page. If you are writing a review about a product, you can include this widget to show the best prices for that product from leading stores in India inside that page itself. <a href="#features" style="color: gray;font-style: italic;font-size: 12px;">More Details</a></p>
					</div>
					<div class="span4 i-block">
						<h3>Products Search Widget</h3>
						<p>For Publishers - Provide an option for users to search for any product in a particular category and check out all the details about the product which includes specifications, best prices and offers.<a href="#features" style="color: gray;font-style: italic;font-size: 12px;">More Details</a></p>
					</div>
					<div class="span4 i-block">
						<h3>Beauty & Fashion Widget</h3>
						<p>For Publishers - If you have content related to beauty and fashion categories, then this widget will help you to show the related products to that content and its avialability and latest price from top sellers. <a href="#features" style="color: gray;font-style: italic;font-size: 12px;">More Details</a></p>
					</div>
				
				</div>
			</div>
		</div>
	</div>
	<!-- End Services Section -->




<!-- Features Section -->
	<div class="section section-alt" id="advertisement">
		<div class="container">
			<div class="content">
				<div class="row">
					<div class="span12">
						<div class="title">
							<h2>Contextual & Dynamic Advertisements</h2>
							<div class="hr hr-small hr-center"><span class="hr-inner"></span></div>
							<p style="font-size:14px;">PlannTo supports contextual targeting at an individual product level and with its real time targeted dynamic display and video advertisements, advertisers can deliver customised, precisely targeted & personalised advertisement with right content at right moment at right place every time.</p>
							<br/><br/>
							<p style="font-size:14px;">Lets take an example of a propsective buyer of Samsung Galaxy S4 reads an review about Samsung Galaxy S4, then its the right moment and right place to show him an advertisement from the advertiser who is selling that product and has offers going on at the moment for that product. PlannTo provides platform to target those kind of users at that place to show the right advertisement based on the content he is interested in. In this case following advertisement related to Samsung Galaxy S4 can be shown to him. Since the advertisements are precisely targeted like this, advertisers can reach their target audience correctly.</p>
						</div>
					</div>
				</div>
				<div style="padding-bottom: 20px;text-align:center;">
					<img src="/images/amazon_s4_ad.png" style="height: 300px;padding-right: 30px;">
				</div>
				<div style="text-align:center;">
					<div>						<h3>Customers</h3>	</div>
					<div class="hr hr-small hr-center"><span class="hr-inner"></span></div>
				<div>
					<img src="http://cdn1.plannto.com/items/vendor/medium/amazon.jpeg" style="height: 40px;padding-right: 40px;">
					<img src="http://cdn1.plannto.com/items/vendor/medium/flipkart.jpeg" style="height: 40px;padding-right: 40px;">
					<img src="http://cdn1.plannto.com/items/vendor/medium/mysmartprice.jpeg" style="height: 40px;padding-right: 20px;">
					<img src="/images/HOU_CENTRESTAGE_LOWER_PINK_RGB_72_DPI_1.png" style="height: 55px;padding-right: 20px;">
					
					</div>
				</div>

						</div>
		</div>
	</div> 
	<!-- End Features -->


	<!-- Features Section -->
	<div class="section section-alt" id="features">
		<div class="container">
			<div class="content">
				<div class="row">
					<div class="span12">
						<div class="title">
							<h2>Widgets</h2>
							<div class="hr hr-small hr-center"><span class="hr-inner"></span></div>
							<p style="font-size:14px;">Javascripts Widgets for Publishers. These widgets can be added to any web pages without much effort. This widget will automatically understand context/product that is discussed in the page and show the right information (best prices/offers) on that page. This widget can be added by adding two lines of javascrict code.</p>
						</div>
					</div>
				</div>
				<div style="padding-bottom: 20px;text-align:center;">
					<img src="/images/BestOffers.png" style="height: 200px;padding-right: 30px;">
					<img src="/images/BestPrice.png" style="height: 200px;padding-right: 30px;">
					<img src="/images/SearchWidget.png" style="height: 200px;">
				</div>
				<div style="text-align:center;">
					<div>						<h3>Customers</h3>	</div>
					<div class="hr hr-small hr-center"><span class="hr-inner"></span></div>
				<div>
					<img src="/images/igyaan.png" style="height: 40px;padding-right: 20px;">
					<img src="/images/gadgetstouse.png" style="height: 30px;padding-right: 20px;">
					<img src="/images/mobigyaan.png" style="height: 30px;padding-right: 20px;">
					<img src="/images/nothingwired.png" style="height: 40px;padding-right: 20px;">
					<img src="/images/technodify.png" style="height: 35px;padding-right: 20px;">
					
					</div>
				</div>

						</div>
		</div>
	</div> 
	<!-- End Features -->


	<!-- About Us section -->
	<div class="section" id="aboutus">
		<div class="container">
			<div class="content">
				<div class="row">
					<div class="span12">
						<div class="title">
							<h2>About Us</h2>
							<div class="hr hr-small hr-center"><span class="hr-inner"></span></div>
							<p>We are trying to change the way how online display and video advertisement works.</p>

						</div>
						
						<p class="text-center" style="font-size:14px;">
						PlannTo is an online contextual advertising platform focussed on optimising display and video advertisements. PlannTo supports contextual targeting at an individual product level and it helps advertisers to connect with prospective buyer of their product using its advanced contextual intelligence and semantic tagging platform. PlannTo complements the product level targeting with its dynamic display/video advertising solutions. With the real time targeted dynamic display and video advertisements, advertisers can deliver customised, precisely targeted & personalised advertisement with right content at right moment at right place every time.
						</p>
						<p class="text-center" style="font-size:14px;">	
						We are bunch of really curious people trying to find the solution to improve the way advertisement works online. If you like to join us, reach us @ admin@plannto.com. 
						</p>
						<p class="text-center">
							
						</p>
					</div>
				</div>
			</div>
		</div> 

	</div>
	<!-- End About US -->

	<!-- Contact Section -->
	<div class="section" id="contact" >
		<div class="container">
			<div class="content">
				<div class="row">
					<div class="span12">
						<div class="title">
							<h2>Contact Us</h2>
							<div class="hr hr-small hr-center"><span class="hr-inner"></span></div>
							<p>We bring a personal and innovative approach to every advertisements served to our customers.</p>

						</div>
					</div>
					<div class="span8">
						<iframe width="100%" height="317" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.in/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Raja Rajeswari Niwas, GB Palya, Bangalore&amp;ll=77.632057,12.897808,0.000000z=13&amp;iwloc=A&amp;output=embed"></iframe>
					</div>
					<div class="span4">
						<h4>Our Location</h4>
						<p>C211, Raja Rajeswari Nivas, Vajpayee Nagar, Bangalore.</p>
						<hr class="grey"/>
						<h4>Email &amp; Phone</h4>
						<p>admin@plannto.com</p>
						<p>(0)9740061994</p>
						<hr class="grey"/>
						<h4>Socialize With Us</h4>
						<div class="social">
							<a href="http://www.facebook.com/PlannTo" style="margin:7px;padding: 0;width: 28px;height: 28px;display: inline-block;vertical-align: middle;"><i class="icon-facebook-sign"></i></a>
							<a href="http://www.twitter.com/PlannTo" style=";margin: 7px;padding: 0;width: 28px;height: 28px;display: inline-block;vertical-align: middle;"><i class="icon-twitter-sign"></i></a>
							<a href="https://plus.google.com/u/0/b/105048081936674725276/" style="margin: 7px;padding: 0;width: 28px;height: 28px;display: inline-block;vertical-align: middle;"><i class="icon-google-plus-sign"></i></a>
						</div>

					</div>
				</div>
			</div>
		</div> 

	</div>
	<!-- End Contact Section -->
	<div id="footer">
		&copy; 2013 PlannTo Technologies Private Limited. <a id="attribution" href="/privacy_policy">Privacy Policy</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a id="attribution" href="/opt_out">Opt Out</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a id="attribution" href="/terms_conditions">Terms and Conditions</a> <br/>
		<div style="
    font-size: 10px;
">Designed with lots of love at <a id="attribution" href="http://www.mrova.com">mRova</a>.</div>
	</div>
</body>
</html>