config/routes.rb
PlanNto::Application.routes.draw do
 
namespace :admin do
  resources :payment_reports
  resources :users
  resources :click_reports
  resources :order_histories do
    collection do
      post "import"
    end
  end
  resources :advertisements do
    collection do
      get "change_ad_status"
      get "review"
      get "approved"
      get "denied"
    end
  end
  resources :buying_plans do
  collection do  
    get :search
    post :search
    get :proposal
    post :proposal_save
    get :proposal_list
   end
   member do
     get  :view_proposal
     get  :proposal_edit
   end
   end
  resources :feeds do
    member do
      get :add_vote
      get :approve
      get :reject
      post :content_action
    end
   end  
  resources :follows
  resources :source_categories, :only => [:index, :update]
 end
  match "sitemap.xml", :to => "sitemap#index", :defaults => {:format => :xml}
  get "home/index"
  resources :follows do
   collection do 
     get :user_follow
   end
  end   
  resources :error_messages

  match "/admin/impression_reports", :to => "admin/order_histories#index"
  match "/admin/orders", :to => "admin/order_histories#orders", :as => :admin_orders
  match "/admin/get_item_details", :to => "admin/order_histories#get_item_details"

  match "/admin/orders/edit/:id", :to => "admin/order_histories#edit", :as => :admin_order_edit
  match "/admin/orders/update", :to => "admin/order_histories#update", :as => :admin_order_update
  match "/admin/orders/delete", :to => "admin/order_histories#destroy", :as => :admin_order_destroy
  match "/admin/get_item_details", :to => "admin/order_histories#get_item_details"

  match "/terms_conditions" ,:to => "home#terms_conditions"
  match "/privacy_policy" ,:to => "home#privacy_policy"
  get "/contact_us" => "contact_us#new"
  match "/about_us",:to => "home#about_us"
  match "/opt_out",:to => "home#opt_out"
  match "/opt_out_submit",:to => "home#opt_out_submit"
  match "/targeting",:to => "home#targeting"
  match "/current_user_info",:to => "home#current_user_info"
  match "/external_page",:to => "products#external_page"
  match "/search_planto",:to => "products#search_items"
  
  match "/get_class_names",:to => "contents#get_class_names"
  match "/external_page",:to => "products#external_page"
  match "/where_to_buy_items",:to => "products#where_to_buy_items"
  match "/where_to_buy_items_vendor",:to => "products#where_to_buy_items_vendor"
  match "/widget_for_women",:to => "products#widget_for_women"
  match "/elec_widget_1",:to => "products#elec_widget_1"
  match "/price_vendor_details",:to => "products#price_vendor_details"
  match "/get_price_from_vendor",:to => "products#get_price_from_vendor"
  match "/price_text_vendor_details",:to => "products#price_text_vendor_details"
  match "/book_price_widget",:to => "products#book_price_widget"
  match "/sports_widget",:to => "products#sports_widget"
  match "/vendor_widget",:to => "products#vendor_widget"
  match "/product_offers",:to => "products#product_offers"
  match "/product_autocomplete",:to => "products#product_autocomplete"
  match "/get_item_for_widget",:to => "products#get_item_for_widget"
  match "/show_search_widget",:to => "products#show_search_widget"
  match "/get_item_item_advertisment",:to => "products#get_item_item_advertisment"
  
  match "/advertisement",:to => "products#advertisement"
  match "/get_class_names",:to => "contents#get_class_names"
  match "products/ratings",:to => "products#ratings"
  
  resources :contact_us
  resources :newuser_wizards do
  collection do
    get :product_select
    get :previous
  end
   member do
    get :product_delete
   end 
  end 
  
  match "/newuser_wizard", :to => "newuser_wizards#new"
  devise_for :users, :controllers => { :sessions => "users/sessions", :registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" ,:passwords => "users/passwords" } 
  resource :oauth,:controller=>"oauth" 

 match "oauth_callback" => "oauth#create"
 match "content_post" => "oauth#content_post"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  

  resources :history_details  
  resources :votes do
    collection do
      post "add_vote"
    end
  end
  match 'external_contents/:content_id' => 'external_contents#show', :as => 'external_content'
  
  match 'admin/search', :to => 'admin#index'
  match ':search_type/search' => 'search#index'
  resources :search do
    collection do
      get :autocomplete_items
      get :preference_items
      get :search_items
      get :autocomplete_source_items
      get :search_items_by_relavance
      get :search_items_by_relavance_housing
    end
  end
  match ':search_type/related-items/:car_id' => 'related_items#index'
  match 'groups/:id' => 'car_groups#show', :as => 'car_groups'
  match ':type/topics' => 'products#topics'
  match 'my_feeds'  => 'contents#my_feeds'

  
resources :field_values, :only => [:create]
resources :answer_contents  

resources :accounts do
    put :update
    member do
      put :change_password
      get :followers
      get :add_review
      get :add_information
      get :add_photo
    end
    collection do
      get :profile
     end 
  end
  match 'account_update', :to => "accounts#update", :as => "account_update"
  match 'personal_deals', :to => "preferences#personal_deals"
 
  resources :preferences do
    collection do
      get :give_advice
      get :owned_item
      get :considered_item_delete
      post :owned_description_save
      get :get_advice
      post :add_preference
      get :create_preference
      post :create_preference
      get  :deals_filter
      get :edit_preference
      post :save_advice
      get :update_preference
      get :plan_to_buy
      get :delete_buying_plan
      delete :delete_buying_plan
      get :update_question
      get :edit_user_question
      delete :delete_answer
      get :edit_answer
      post :update_answer
    end
    
  end
   match 'create_buying_plan' => 'preferences#new'
   match 'preferences/:search_type/:uuid' => 'preferences#show'
   match ':itemtype/guides/:guide_type' => 'contents#search_guide'
   match ':itemtype/:item_id/guides/:guide_type' => 'contents#search_guide'
   
  resources :cars do
        resources :reports
        resources :shares
  end
   

  resources :contents do
   resources :reports 
  collection do
    get :filter
    get :edit_guide_ajax
    post :update_guide
    get :feed
    get :feeds
    post :search_contents
    get :search_autocomplete_list
    get :search_related_contents
    get :quick_new
  end
  match "/contents/search" => 'contents#search'
 
  post :search
  resources :comments 
    collection do
      get :feed
    end
  end
resources :comments do
    resources :reports 
   end 
  resources :event_contents
  resources :plannto_contents
  resources :article_contents do
    put :download
    collection do
      post :download
      post :new_popup
      get :bmarklet
      put :download
    end
  end
  resources :mobiles do
        resources :shares
  end 
  resources :tablets do
        resources :shares
  end 
  resources :cameras do
        resources :shares
  end  
  resources :games do
        resources :shares
  end  
  resources :laptops do
        resources :shares
  end  
  resources :bikes do
        resources :shares
  end   
  resources :cycles do
        resources :shares
  end
  resources :lens do
    resources :shares
  end
  resources :televisions do
    resources :shares
  end
  resources :wearable_gadgets do
    resources :shares
  end
  resources :consoles do
    resources :shares
  end
  resources :beauties do
    resources :shares
  end
  resources :countries do
    resources :shares
  end
  resources :states do
    resources :shares
  end
  resources :cities do
    resources :shares
  end
  resources :places do
    resources :shares
  end
  resources :mobiles do 
    resources :reports
  end  
  resources :tablets do 
    resources :reports
   end 
  resources :vendors do 
    resources :reports
   end 
  resources :cameras do 
    resources :reports
  end  
  resources :bikes do
    resources :reports
  end  
  resources :cycles do
    resources :reports
  end
  resources :lens do
    resources :reports
  end
  resources :televisions do
    resources :reports
  end
  resources :wearable_gadgets do
    resources :reports
  end
  resources :consoles do
    resources :reports
  end
  resources :beauties do
    resources :reports
  end
  resources :countries do
    resources :reports
  end
  resources :states do
    resources :reports
  end
  resources :cities do
    resources :reports
  end
  resources :places do
    resources :reports
  end
  resources :bike_groups
  resources :manufacturers
  resources :car_groups  
  resources :attribute_tags
  resources :topics
  resource :facebook, :except => :create do
    get :callback, :to => :create
    get :friends
    get :wall_post
    get :show_friends
    post :wall_content
  end
  resources :products do
    collection do
      get 'related_items'
      get 'follow_buttons'
    end
    member do
      get 'related_products'
      get 'specification'
      get 'review_it'
      get 'add_item_info'
    end
  end
  resources :items do
       resources :reports    
    collection do
      get :compare
      get :update_page
      get :remove_duplicate_item
    end
    member do
      get 'follow_item_type'
      get 'plan_to_buy_item'
      get 'own_a_item'
      get 'follow_this_item'
    end
  end
  resources :reviews
  resources :review_contents
  resources :question_contents
  resources :pros
  resources :questions
  resources :answers
  resources :tips
  resources :invitations
  resources :processes, :only => [:index] do
    collection do
      get "item_update"
    end
  end

  match 'invitation/accept/:token' => "invitations#accept", :as => :accept_invitation
    
  resources :imageuploads, :only => [:show] 
  match "/imageuploads_tag" => 'imageuploads#tag' 

app/models/report.rb
class Report < ActiveRecord::Base
   ReportTypes = [["Duplicate Content","Duplicate Content"],["Copyright Issue","Copyright Issue"],["Spam","Spam"],["Others","Others"]] 
   validates_presence_of :report_type
   validates_presence_of :description
   belongs_to :reportable, :polymorphic => true
   belongs_to :user, :foreign_key => 'reported_by'
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
 before_filter :authenticate_user!
 before_filter :find_reportable_object
 
 def index
 
 end
 
 def new
   @report = Report.new
   @type = params[:type]
  end

 def create
   @report = @reportable_object.reports.create(params[:report])
   @report.reported_by = current_user.id
   @report.report_from_page = session[:return_to]
   @report.save
 end

 def article_reports
   @start_date = params[:from_date].blank? ? 1.week.ago : params[:from_date].to_date
   @end_date = params[:to_date].blank? ? Time.zone.now : params[:to_date].to_date

   @results = ArticleContent.reports_from_article_content(@start_date, @end_date)

   render :layout => "product"
 end

  private

  def find_reportable_object
    if params[:type] == "content" 
      @reportable_object = Content.find(params[:content_id])
    elsif params[:type] == "comment"
      @reportable_object = Comment.find(params[:comment_id]) 
    elsif params[:type] == "dealer"
      @reportable_object = Item.find(params[:item_id])
   end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_dealer.html.erb
 <%= javascript_include_tag "/javascripts/expanding.js" %>
 
 <%= form_for @report,:url => item_reports_path(@reportable_object),:remote => true,:id => "report_form" do |f| %>
<div class="popup-background">
   <a href="#" class="Closebut">&nbsp;</a>
 <div ID="new_answer_content_block" style="padding:5px 5px 0px 5px;height:150px;">  
     <div style="padding:5px 5px 0px 0px;text-align:center">
      <%= hidden_field_tag :type,@type %>
   
 <span class="Popuptitle"><center> <h1>Report</h1> </center></span>
 <br/>
    <div class="productreview" style="clear:both;width:250px;">
        <div class="title_header float_lft"">Report Type :</div>  <%= f.select :report_type,[["Dealer/seller","Dealer/seller"]] %></div>
</div>
<br />
    <div style="padding:0px 500px 0px 5px;">
        <div class="title_header float_lft">Description :</div>
        <div style="margin-left:80px;">
       <%= f.text_area :description, :class => 'textFilling expanding', :id=>"report",:style=> 'width:400px;height:50px;' %>
     </div>
      </div>
    </div>
    <br />
    <br />
     <br />
    <br />
    <div style="padding:100px 0px 0px 900px; float:right; width:100%; margin-right:5px; margin-top:20px ">
        <%= f.submit 'Send report', :class => 'btn_submitanswer',:id => "publishanswer" %>
        <%= render "shared/ajax_loader" %>
    </div>
    <div style="clear:both;"></div>
</div>
<% end %>
<%= render "shared/expanding_text_area_style" %>
<div style="clear:both;"></div>
<script> 
  $("#report").val("");
</script>
</div>

app/views/reports/_new.html.erb
<%= form_for @report,:url => @type == "content" ? content_reports_path(@reportable_object) :  comment_reports_path(@reportable_object),:remote => true,:id => "report_form" do |f| %>
<%= javascript_include_tag "/javascripts/expanding.js" %>
<div class="popup-background">
   <a href="#" class="Closebut">&nbsp;</a>
 <div ID="new_answer_content_block" style="padding:5px 5px 0px 5px;height:150px;">  
     <div style="padding:5px 5px 0px 0px;text-align:center">
     <%= hidden_field_tag :type,@type %>
     <div style="clear:both;"></div>
 <span class="Popuptitle"><center> <h1>Report</h1> </center></span>
 <br/>
    <div class="productreview" style="clear:both;width:250px;">
        <div class="title_header float_lft"">Report Type :</div>  <%= f.select :report_type,Report::ReportTypes %></div>
</div>
<br />
<div style="clear:both;"></div>
    <div style="padding:0px 500px 0px 5px;">
        <div class="title_header float_lft">Description :</div>
        <div style="margin-left:80px;">
       <%= f.text_area :description, :class => 'textFilling expanding', :id=>"report",:style=> 'width:400px;height:50px;' %>
     </div>
      </div>
    </div>
    <br />
    <br />
     <br />
    <br />
    <div style="clear:both;"></div>
    <div style="padding:100px 0px 0px 900px; float:right; width:100%; margin-right:5px; margin-top:20px ">
        <%= f.submit 'Send report', :class => 'btn_submitanswer',:id => "publishanswer" %>
        <%= render "shared/ajax_loader" %>
    </div>
    <div style="clear:both;"></div>
</div>
<% end %>
<%= render "shared/expanding_text_area_style" %>

<script> 
  $("#report").val("");
</script>
</div>

app/views/reports/article_reports.html.erb
<h3 class="report_title">
  Widgets Reports
</h3>

<br/>

<%= form_for :impression, :url => reports_article_reports_path, :method => :get do |f| %>
    <div>
<span style="width:100px;display:block;float:left;padding-top:5px;">
Select A date Range
</span>
<span style="width: 100px;display: block;float: left;height: 20px;text-align: center;padding-top: 5px;">

	<%= select_tag(:date_from_dropdown, options_for_select([["Select a date Range", 0], ['Yesterday', 1], ['Last Week', 7], ['Last month', 30], ['Last 3 months', 90], ['Last 6 Months', 180]])) %>
</span>

      <script>
          $("#date_from_dropdown").live("change", function () {
              days = $(this).val();
              var date = new Date();
              date.setDate(date.getDate() - days);
              var from_date = date.getDate() + '-' + (date.getMonth() + 1) + '-' + date.getFullYear();
              $("#from_date").val(from_date);
              date = new Date();
              // date.setDate(date.getDate() - 1);
              var to_date = date.getDate() + '-' + (date.getMonth() + 1) + '-' + date.getFullYear();
              $("#to_date").val(to_date);
          });
      </script>
      <br/>
      <br/>
      <br/>
	<span style="width:100px;display:block;float:left;padding-top:5px;">
From Date
</span>
<span style="width: 100px;display: block;float: left;height: 20px;text-align: center;padding-top: 5px;">
<%= text_field_tag :from_date, @start_date.to_date.strftime("%d-%m-%Y"), :style => "padding:2px;width:100px;" %>
</span>
      <script>
          $("#from_date").datepicker({ dateFormat: 'dd-mm-yy' });
      </script>
      <br/>
    </div>
    <div style="display:block;padding-top:10px;clear:both;">
<span style="width:100px;display:block;float:left;padding-top:5px;">
To Date
</span>
<span style="width: 100px;display: block;float: left;height: 20px;text-align: center;padding-top: 5px;">
<%= text_field_tag :to_date, @end_date.to_date.strftime("%d-%m-%Y"), :style => "padding:2px;width:100px;" %>
</span>
    </div>


    <div style="width:200px;padding-left:100px;display:block;clear:both;padding-top:20px;">
      <%= f.submit 'Generate Report', :class => "btn-link" %>
    </div>
<% end %>
<script>
    $("#to_date").datepicker({ dateFormat: 'dd-mm-yy' });
</script>
<div style="border-bottom: 1px solid lightgray;width: 100%;clear: both;padding-top: 10px;"></div><br/><br/>
<!--
<div id="report">
  <%#= render "admin/ad_reports/widget_chart" %>
</div>
-->

<br /><br />

<div id="report" >
  <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
      <th class="header_compare" width="80px"> Created By </th>
      <th class="header_compare" width="80px"> Created Type </th>
      <th class="header_compare" width="80px"> Count </th>

    </tr>
    <% @results.each do |result | %>
        <tr>
          <td class="bdb_gray1" width="80px" style="text-align:center;border-bottom: 1px solid #808080;">
            <%= result.created_by %>
          </td>
          <td class="bdb_gray1" width="80px" style="text-align:center;border-bottom: 1px solid #808080;">
            <%= result.created_type %>
          </td>
          <td class="bdb_gray1" width="80px" style="text-align:center;border-bottom: 1px solid #808080;">
            <%= result.count %>
          </td>
        </tr>
    <%end%>

  </table>
</div>


<style type="text/css">

    .list_titles {
        height: 30px;
    }

    .list_title {
        float: left;
        font-weight: bold;
        font-size: 13px;
    }

    .list_values {
        clear: both;
        height: 26px;
    }

    .ad_value {
        float: left;
        font-size: 12px;
    }

    .ad_name {
        padding-left: 30px;
        width: 151px;
    }

    .ad_budget {
        width: 75px;
    }

    .ad_bid {
        width: 75px;
    }

    .ad_cost {
        width: 75px;
    }

    .ad_impressions {
        width: 94px;
    }

    .ad_clicks {
        width: 75px;
    }

    .ad_ecpm {
        width: 75px;
    }

    .ad_ectr {
        width: 75px;
    }

    .ad_chart_view {
        width: 75px;
    }

    .advertisement_list {
        margin: 20px;
    }

    .report_title {
        font-size: 24px;
        margin: 20px;
        text-align: center;
    }

</style>

app/views/reports/create.js.erb
 $(".Closebut").click()
window.location.reload();

app/views/reports/new.js.erb
<%if @type == "dealer" %>
  $("#dealer_report").html("<%= escape_javascript(render "reports/dealer",:type => @type,:reportable_object => @reportable_object,:report => @report) %>");
   $(".Closebut").click()
  $("#dealer_report").bPopup({
    closeClass:'Closebut',
    modalClose: false,
    position: [(screen.width / 2) - (520/2), $(window).scrollTop() + 120],
    follow: [false, false] //x, y
 });
 
 <%else%> 
    $("#contentEditView").html("");
  $("#contentEditView").html("<%= escape_javascript(render "reports/new",:type => @type,:reportable_object => @reportable_object,:report => @report) %>");
  $(".Closebut").click();
  $("#contentEditView").bPopup({
    closeClass:'Closebut',
    modalClose: false,
    position: [(screen.width / 2) - (520/2), $(window).scrollTop() + 120],
    follow: [false, false] //x, y
 });
 <%end%>